### PR TITLE
Using proguard to strip redundant classes

### PR DESCRIPTION
**Pull request by nisrulz**
addresses issue #17 . Using proguard strip everything out except the Range class of guava and the classes from the library

### CODE REVIEW

**Comment by thyrlian** [comment]
@nisrulz Thanks for your great work.

* yes, build is passed now
* all lib update makes sense
* I will have a deeper look when I have time
* regarding stripping unnecessary classes from Guava, are you sure that ```keep class com.google.common.collect.Range``` is enough?  I think that is just to keep specified class from obfuscation.

Thanks.

**Comment by nisrulz** [comment]
>regarding stripping unnecessary classes from Guava, are you sure that keep class com.google.common.collect.Range is enough?

As per the [Official Proguard Manual](https://stuff.mit.edu/afs/sipb/project/android/sdk/android-sdk-linux/tools/proguard/docs/index.html#manual/usage.html) 
+  `-keep` : Specifies classes and class members (fields and methods) to be preserved as entry points to your code.

on the other hand there are other flags to do what you specified  
> I think that is just to keep specified class from obfuscation

you can have a look at the official link regarding  `-keepclasseswithmembernames`, `-keepclassmembernames`  and `-keepnames`

Anyways I will eventually want to configure proguard to list all the files it has removed. Will do that as soon as I get time to.

**Comment by thyrlian** [comment]
@nisrulz thanks a bunch for explanation and the links, I'll check them later :)

**Comment by thyrlian** [comment]
@nisrulz I just checkout your branch, and tested via dexcount-gradle-plugin, it seems like the unused classes inside Guava are not really stripped away:

**Before**:
==================================================
```
13666    3265     com.google
13649    3256     com.google.common
3        0        com.google.common.annotations
876      325      com.google.common.base
7        6        com.google.common.base.internal
849      282      com.google.common.cache
8231     1553     com.google.common.collect
74       29       com.google.common.escape
65       28       com.google.common.eventbus
490      120      com.google.common.hash
3        1        com.google.common.html
616      141      com.google.common.io
102      39       com.google.common.math
144      214      com.google.common.net
556      104      com.google.common.primitives
511      91       com.google.common.reflect
1125     324      com.google.common.util
1125     324      com.google.common.util.concurrent
4        5        com.google.common.xml
17       9        com.google.thirdparty
17       9        com.google.thirdparty.publicsuffix
```
==================================================

**After**:
==================================================
```
13889    3345     com.google
13872    3336     com.google.common
3        0        com.google.common.annotations
944      343      com.google.common.base
7        6        com.google.common.base.internal
858      282      com.google.common.cache
8143     1558     com.google.common.collect
74       29       com.google.common.escape
95       35       com.google.common.eventbus
498      120      com.google.common.hash
3        1        com.google.common.html
614      141      com.google.common.io
118      41       com.google.common.math
146      221      com.google.common.net
558      104      com.google.common.primitives
533      98       com.google.common.reflect
1281     358      com.google.common.util
1281     358      com.google.common.util.concurrent
4        5        com.google.common.xml
17       9        com.google.thirdparty
17       9        com.google.thirdparty.publicsuffix
```
==================================================

The minor differences are due to Guava library's update.

**Comment by thyrlian** [comment]
Thanks @nisrulz for contributing :+1: 
I've merged your changes.

But unfortunately this still doesn't strip away unused Guava classes :(

**Comment by nisrulz** [comment]
@thyrlian thanks for the merge, I will update my code with changes to address the issue and a  detailed method check as soon as I get the time.
However I would certainly look into this why Proguard didn't strip the other classes from guava.

**Pull request merged**
