### PR TITLE
Migrating to Androidx

### PR DESCRIPTION
**Pull request by eTryp**
- Update project with the last SDK version 28 (Pi)
- Update support library to androidx

### CODE REVIEW

**Comment by thyrlian** [comment]
Thanks for the PR, could you please fix the build error?

```console
* What went wrong:
A problem occurred configuring project ':demo'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
     platforms;android-28 Android SDK Platform 28
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html
```

**Comment by eTryp** [comment]
Hi,

You just have to accept the SDK license agreements to make it working. Nothing to fix on my side.

Regards
________________________________
De : Jing Li <notifications@github.com>
Envoyé : samedi, février 16, 2019 7:20 AM
À : thyrlian/AwesomeValidation
Cc : movryp; Author
Objet : Re: [thyrlian/AwesomeValidation] Migrating to Androidx (#72)


Thanks for the PR, could you please fix the build error?

* What went wrong:A problem occurred configuring project ':demo'.> Failed to install the following Android SDK packages as some licences have not been accepted.     build-tools;28.0.3 Android SDK Build-Tools 28.0.3     platforms;android-28 Android SDK Platform 28  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.  Alternatively, to transfer the license agreements from one workstation to another, see http://d.android.com/r/studio-ui/export-licenses.html

**Comment by thyrlian** [comment]
Hi,

I mean the CI is failing, you should fix it otherwise I can't merge it.

https://travis-ci.org/thyrlian/AwesomeValidation/builds/492697018?utm_source=github_status&utm_medium=notification

Thanks.

**Comment by thyrlian** [comment]
Done by #84 from @temirnurdin.  Because his PR passed all checks and review, already merged.  So I'm closing this one now.  Sorry but thanks for your try.

**Pull request closed without merging**
