### PR TITLE
Add new addValidation polymorphism with View as param

### PR DESCRIPTION
**Pull request by elsennov**
Add new addValidation polymorphism with View as param. It is very useful if the validated view is not inflated on the activity view.

### CODE REVIEW

**Comment by thyrlian** [comment]
Hi @elsennov , it sounds good, I'll check it out later when I have time.

And I'm so happy that you've also added examples in demo, that makes it much easier :+1: 

Thanks for your contribution :)

**Comment by elsennov** [comment]
Hi @thyrlian ,
I am so glad that i could contribute to this awesome validation. Yes please, you are welcome :)

**Comment by thyrlian** [comment]
Hi @elsennov ,

Sorry for my late reply, coz I just got time to check it thoroughly.  Your code is good, and it works fine, thanks for that :)

The question is, as you mentioned in the commit - "It is useful if the validated view is not inflated on the activity view".  While the change you did in the demo project is still inflated to the same activity.  It would be great if you could elaborate a better example, thanks.

Explain it by comments is enough, and later we can see how should we change the demo.

Thanks again :+1:

**Comment by elsennov** [comment]
Hi @thyrlian , i have added the demo for it. Basically, this pull request will allow us to use view instead of activity to get the edittext based on the resource id.
From the current version, if we pass edit text id, it will search only from activity. So, i made this, to search the edittext from the view.

**Comment by thyrlian** [comment]
Thanks @elsennov for adding a fragment demo, I'll check it out when time allows :+1:

**Comment by thyrlian** [comment]
Sorry @elsennov for my late reply (was busy due to some family stuff).

After checking your commits, I have several thoughts:

1. Actually we don't really need to overload ***set*** method or ***addValidation*** method to accept ***View rootView*** parameter.  Because they already accept ***EditText editText*** parameter (the view to be validated).  So that you can do `EditText editText = (EditText) rootView.findViewById(viewId)` outside, and pass the editText in (please check [here](https://github.com/thyrlian/AwesomeValidation/blob/master/library/src/main/java/com/basgeekball/awesomevalidation/AwesomeValidation.java#L56-L58)).

2. After your modification, the DemoActivity now is mixed with validations in the activity, and validations in the fragment.  I think if we want to make it clear, we should build a better structure (with three different scenarios, and each of them has a solution based on current implementation):
 * Validations only in activity (no nested fragment)
   * the solution is exactly what the DemoActivity tells.
 * Validations only in fragment (activity body is empty)
   * similar to validation in activity, just move all validation code to fragment
 * Validations in activity and fragment (activity has nested fragment)
    * you could split validations into different places (activity and fragment), depends on which makes sense to you
    * you can keep all validation code in activity, which is cleaner and simpler (as long as the view in the fragment has an id, the addValidation API works for it)
    * if the fragment (and its validation) is reused by several different activities, so that you want to keep the validation code inside that fragment; meanwhile in each different activity, they have their own validation, and you want to trigger both fragment validation and activity validation in some listener from activity, then please add some new interface (e.g. ValidatableFragment), then implement the interface, call it at expected place:
   ```java
public interface ValidatableFragment {
    AwesomeValidation add(AwesomeValidation awesomeValidation);  // return AwesomeValidation object back to activity, prevent memory leak when refer to it (because it could hold activity)
    void triggerValidation();  // you can hold an AwesomeValidation object inside fragment, but at your own risk, as for example UnderlabelValidator is referring to Context
}
   ```
3. In your fragment code, there is potential risk that could lead to memory leak (because of strong reference to activity).  You are calling `initAwesomeValidation` in `onCreateView `, while `initAwesomeValidation` set context by `setContext(getActivity())`.  But you didn't release the strong reference of the activity / context by setting mAwesomeValidation to null in `onDetach()`.

Come to the conclusion: Sorry, I have to close your pull request, as I explained above (you can make it work by current implementation).  But many thanks to your great work and support. :+1:

**Pull request closed without merging**
